name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ['1.25']
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./cmd/tufzy

      - name: Test
        run: go test -v ./...

      - name: Smoke test
        run: |
          ./tufzy list https://jku.github.io/tuf-demo/metadata
          ./tufzy info https://jku.github.io/tuf-demo/metadata
          ./tufzy delegations https://jku.github.io/tuf-demo/metadata

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
